@startuml

class BaseWidget {
    isActive: bool
}

class ListWidget {
    widget: *widgets.List
}

class RegionListWidget {
}

class ServiceListWidget {
}

class ServiceInstanceListWidget {
}


BaseWidget *-down- ListWidget
ListWidget *-right- RegionListWidget
ListWidget *-right- ServiceListWidget
ListWidget *-down- ServiceInstanceListWidget

RegionListWidget -[hidden]down- ServiceListWidget

class LambdaInstanceListWidget {
}

class DynamoDBInstanceListWidget {
}

class EC2InstanceListWidget {
}

class S3InstanceListWidget {
}

ServiceInstanceListWidget o-down- LambdaInstanceListWidget
ServiceInstanceListWidget o-down- DynamoDBInstanceListWidget
ServiceInstanceListWidget o-down- EC2InstanceListWidget
ServiceInstanceListWidget o-down- S3InstanceListWidget

@enduml