@startuml

interface View {
    +GetSelectedData(): string
    +HandleEvent(event string)
    +Render()
}

class ListView {
	-listWidget: *widgets.List
	+SetData(listData []string)
    +GetSelectedData(): string
    +HandleEvent(event string)
    +Render()
    +ScrollUp()
    +ScrollDown()
}

class RegionListView {
    +Render()
}

class ServiceListView {
    +Render()
}

class ServiceInstanceListView {
    +Render()
}

View <|.down. RegionListView
View <|.down. ServiceListView
View <|.down. ServiceInstanceListView
View <|.down. LambdaInstanceView
View <|.down. DynamoDBInstanceView
View <|.down. EC2InstanceView
View <|.down. S3InstanceView

class LambdaInstanceView {
    +SetData()
    +Render()
}

class DynamoDBInstanceView {
    +SetData()
    +Render()
}

class EC2InstanceView {
    +SetData()
    +Render()
}

class S3InstanceView {
    +SetData()
    +Render()
}

ListView *-up- RegionListView
ListView *-up- ServiceListView
ListView *-up- ServiceInstanceListView

@enduml