@startuml

class ListView {
	-listWidget: *widgets.List
	+SetData(listData []string)
    +GetSelectedData()
    +Render()
    +ScrollUp()
    +ScrollDown()
}

class RegionListView {
}

class ServiceListView {
}

class ServiceInstanceListView {
}

class LambdaInstanceView {
    SetData()
    Render()
}

class DynamoDBInstanceView {
    SetData()
    Render()
}

class EC2InstanceView {
    SetData()
    Render()
}

class S3InstanceView {
    SetData()
    Render()
}

ListView *-down- RegionListView
ListView *-down- ServiceListView
ListView *-down- ServiceInstanceListView

@enduml